### ISSUE TITLE
Cable Unplugged in Monterey

### ISSUE THREAD

**Issue by THLIVSQAZ** [Mieze/RTL8111_driver_for_OS_X#73]
mac version: 12.0.1(21A559)
ethernet card :
![Screen Shot 2021-10-28 at 12 56 25 AM](https://user-images.githubusercontent.com/25531652/139248474-382a54d3-d2da-4cc4-b06c-bf66b6f655cd.png)

problem: 
![Screen Shot 2021-10-28 at 12 57 11 AM](https://user-images.githubusercontent.com/25531652/139248549-ace79467-caca-4e75-9fe5-61d2821653b6.png)
![Screen Shot 2021-10-28 at 12 57 35 AM](https://user-images.githubusercontent.com/25531652/139248619-7ad92ad8-ecee-4b8e-b871-aeb4b2d7f46f.png)
kextLoad:
![Screen Shot 2021-10-28 at 2 46 16 PM](https://user-images.githubusercontent.com/25531652/139248769-d9251126-a040-4b9f-9399-f1c5ce605178.png)

system is new install ,not OTA upgrade from big sur
I also try to install to /L/E and disable sip ,switch the speed ,deleted and reseted preference ,all not working

network status led on router and motherboard is working, if I use command "sudo ifconfig en0 down" the leds is off , and use "sudo ifconfig en0 up" is on

i didn't found the log in log show and /var/log/system.log, so i take photo when boot up
![1](https://user-images.githubusercontent.com/25531652/139249595-3f882718-610c-48d3-9285-aa033c707218.png)
![2](https://user-images.githubusercontent.com/25531652/139249628-b650060e-b4ed-4caa-bf2e-ef1092215d38.png)

**Comment by vincerutabaga** [comment]
In monterey 12.2.1 with kext v.2.4.2 it work great.
But it's a pcie card, not onboard nic. Monterey have been hard with all onboard nic.
Thanks meize!

**Comment by Benau** [comment]
I'm trying to debug now and seems that `interruptOccurredPoll` doesn't debuglog blah blah blah at all in 12.3, maybe msiIndex is wrong?

**Comment by Benau** [comment]
Maybe 12.3 handles
```
    while ((intrResult = pciDevice->getInterruptType(intrIndex, &intrType)) == kIOReturnSuccess) {
        if (intrType & kIOInterruptTypePCIMessaged){
            msiIndex = intrIndex;
            break;
        }
        intrIndex++;
    }
```
differently, maybe some new (fake!) devices will break eariler

**Comment by willianfrs** [comment]
Dears, I was also having this problem, I used a RehabMan driver and it is working on Monterey. Can I post the link here for that driver? I don't know, maybe I can help with the solution...

**Comment by Benau** [comment]
BTW it seems that intrType & kIOInterruptTypePCIMessaged is true for 1 2 3 4 with my onboard lan too
In https://github.com/Benau/RTL8111_driver_for_OS_X/commit/fcd42d647b1b0b936b48eabf22f3884a8595a41d, I manually 'poll' interrupt and it seems to work fine with both rxPoll on / off, @THLIVSQAZ can you try this Kext and see if it works? (and does my commit make sense, I'm a noob kernel programmer)

[RealtekRTL8111.zip](https://github.com/Mieze/RTL8111_driver_for_OS_X/files/8414872/RealtekRTL8111.zip)

(you can false disableMSI in Info.plist later if you have got a non-onboard rtl8111)

**Comment by blacksd** [comment]
@Benau happy to report that your driver change actually fixed my on-board card. 

```
Realtek RTL8168GU/8111GU PCI Express Gigabit Ethernet:

  Bus:	                PCI
  Vendor ID:	        0x10ec
  Device ID:	        0x8168
  Subsystem Vendor ID:	0x1028
  Subsystem ID:	        0x0706
  Revision ID:	        0x0010
  PCIe Link Speed:	2.5 GT/s
  PCIe Link Width:	x1
  Driver:	        com.insanelymac.RealtekRTL8111
  BSD Device Name:      en0
  MAC Address:	        <REDACTED>
  AVB Support:	        No
  Maximum Link Speed:   1 Gb/s
```

Even with the automatic link discovery, it works like a charm.

**Comment by Benau** [comment]
Nice!

@Mieze can you see if my commit make sense for you? Or do you have a better idea instead of keep polling the card every 1ms?

BTW even changing msiindex to 2, 3 or 4 still doesn't work

**Comment by willianfrs** [comment]
> BTW it seems that intrType & kIOInterruptTypePCIMessaged is true for 1 2 3 4 with my onboard lan too In [Benau@fcd42d6](https://github.com/Benau/RTL8111_driver_for_OS_X/commit/fcd42d647b1b0b936b48eabf22f3884a8595a41d), I manually 'poll' interrupt and it seems to work fine with both rxPoll on / off, @THLIVSQAZ can you try this Kext and see if it works? (and does my commit make sense, I'm a noob kernel programmer)
> 
> [RealtekRTL8111.zip](https://github.com/Mieze/RTL8111_driver_for_OS_X/files/8414872/RealtekRTL8111.zip)
> 
> (you can false disableMSI in Info.plist later if you have got a non-onboard rtl8111)

Thank you so much for making this kext available. Fitting also solved my problem here. Thanks.

**Comment by dhavalhirdhav** [comment]
> 

This kext file works really well for AMD Ryzen 3 3200G. Been struggling since couple of days. Thanks :) Should release this patch as many are facing this issue.

**Comment by Hesowcharov** [comment]
> BTW it seems that intrType & kIOInterruptTypePCIMessaged is true for 1 2 3 4 with my onboard lan too In [Benau@fcd42d6](https://github.com/Benau/RTL8111_driver_for_OS_X/commit/fcd42d647b1b0b936b48eabf22f3884a8595a41d), I manually 'poll' interrupt and it seems to work fine with both rxPoll on / off, @THLIVSQAZ can you try this Kext and see if it works? (and does my commit make sense, I'm a noob kernel programmer)
> 
> [RealtekRTL8111.zip](https://github.com/Mieze/RTL8111_driver_for_OS_X/files/8414872/RealtekRTL8111.zip)
> 
> (you can false disableMSI in Info.plist later if you have got a non-onboard rtl8111)

@Benau (cc @Mieze) I can also approve that fix works (at least at first glance)! Please consider to review and pull the changes

**Comment by Mieze** [comment]
If the driver is unable to pick up the matching interrupt, that's clearly an ACPI related problem and problems should be solved at the origin. I know, macOS is becoming more picky on that with every release but that's not my fault. Permanently polling the device makes no sense and I'm not willing to integrate such a patch.

**Comment by blacksd** [comment]
@Mieze I understand that this patch is not a solution, and should not be merged, but shall we keep this issue open - at least as to have a proper place to look for another solution and/or make people aware of the current limitation?

**Comment by adrianlungu** [comment]
Unfortunately, I tried the kext from @Benau on my end but it didn't want to budge. Still getting `cable unplugged`. 

Tried other versions of the kext as well and it was a no go. 

I'm not sure what to go for SSDT-wise, but I'm open to any suggestions to get this working!

**Comment by Kissadere** [comment]
> BTW it seems that intrType & kIOInterruptTypePCIMessaged is true for 1 2 3 4 with my onboard lan too In [Benau@fcd42d6](https://github.com/Benau/RTL8111_driver_for_OS_X/commit/fcd42d647b1b0b936b48eabf22f3884a8595a41d), I manually 'poll' interrupt and it seems to work fine with both rxPoll on / off, @THLIVSQAZ can you try this Kext and see if it works? (and does my commit make sense, I'm a noob kernel programmer)
> 
> [RealtekRTL8111.zip](https://github.com/Mieze/RTL8111_driver_for_OS_X/files/8414872/RealtekRTL8111.zip)
> 
> (you can false disableMSI in Info.plist later if you have got a non-onboard rtl8111)

You soled my issue (and probably many other's people issues too). 

You rock!
